export const queryKeys = {
  me: ["auth", "me"] as const,
  studentDashboard: (userId: string) => ["student", "dashboard", userId] as const,
  studentHistory: (userId: string) => ["student", "history", userId] as const,
  studentHistoryPage: (userId: string, query: object) => ["student", "history", userId, "page", query] as const,
  artifact: (id: string) => ["artifact", id] as const,
  myArtifactReports: (artifactId: string) => ["artifact", artifactId, "my-reports"] as const,
  artifactsPage: (query: object) => ["admin", "artifacts", query] as const,
  assessment: (type: "pretest" | "posttest") => ["assessment", type] as const,
  assessmentAttemptActive: (type: "pretest" | "posttest") => ["assessment", type, "attempt", "active"] as const,
  assessmentDraft: (type: "pretest" | "posttest", attemptId: string) =>
    ["assessment", type, "attempt", attemptId, "draft"] as const,
  assessmentSubmissionsPage: (query: object) => ["admin", "assessment-submissions", "page", query] as const,
  assessmentItemStats: (type: "pretest" | "posttest", group: "adaptive" | "static" | "all") =>
    ["admin", "assessment-item-stats", type, group] as const,
  assessmentGains: ["admin", "assessment-gains"] as const,
  pretest: ["assessment", "pretest"] as const,
  posttest: ["assessment", "posttest"] as const,
  survey: ["survey", "usability"] as const,
  adminSurveyQuestions: ["admin", "survey", "questions"] as const,
  adminSurveyResponses: ["admin", "survey", "responses"] as const,
  adminOverview: ["admin", "overview"] as const,
  operationalAlertsSummary: (windowHours: number, limit: number) =>
    ["admin", "ops", "alerts", windowHours, limit] as const,
  studentsPage: (query: object) => ["admin", "students", "page", query] as const,
  studentInvitesPage: (query: object) => ["admin", "student-invites", "page", query] as const,
  artifactIssueReportsPage: (query: object) => ["admin", "artifact-issue-reports", "page", query] as const,
  telemetryEventsPage: (query: object) => ["admin", "events", "page", query] as const,
  telemetrySummary: (query: object) => ["admin", "events", "summary", query] as const,
  studentProtocol: (userId: string) => ["admin", "students", userId, "protocol"] as const,
  studentProtocolAuditPage: (userId: string, query: object) => ["admin", "students", userId, "protocol", "audit", query] as const,
  students: ["admin", "students"] as const,
  studentInvites: ["admin", "student-invites"] as const,
  artifactIssueReports: ["admin", "artifact-issue-reports"] as const,
  corpusDatasetsPage: (query: object) => ["admin", "corpus", "datasets", "page", query] as const,
  corpusDatasetChunksPage: (datasetId: string, query: object) =>
    ["admin", "corpus", "datasets", datasetId, "chunks", query] as const,
  asyncJobsPage: (query: object) => ["admin", "jobs", "page", query] as const,
  asyncJob: (jobId: string) => ["admin", "jobs", jobId] as const,
  artifactCoverage: ["admin", "artifacts", "coverage"] as const,
};
